---
title: "ggplot2"
author: "Yang Gao"
date: "10/7/2021"
output: github_document
---

```{r}
library (tidyverse)
library (viridis)
library (patchwork)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather_df
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  labs(
    title = "Temperature at three stations",
    x= "Minimum daily temp (C)",
    y= "Maximum daily temp (C)",
    caption = "Data from the rnoaa package with three stations"
  ) +
    scale_color_hue( name ="location", h = c(100, 200) ) + scale_color_viridis_d()
                    


weather_df
```

## Scales
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  labs(
    title = "Temperature at three stations",
    x= "Minimum daily temp (C)",
    y= "Maximum daily temp (C)",
    caption = "Data from the rnoaa package with three stations"
  ) +
    scale_x_continuous(
    breaks = c(-15, 0, 15), 
    labels = c("-15ยบ C", "0", "15") ) +
    
    scale_y_continuous(
      trans = "sqrt", 
    position = "right"
    )
    
    

weather_df
```


## Themes
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  labs(
    title = "Temperature at three stations",
    x= "Minimum daily temp (C)",
    y= "Maximum daily temp (C)",
    caption = "Data from the rnoaa package with three stations") +
  
    scale_color_hue( name ="location", h = c(100, 300)) + 
    scale_color_viridis_d() +
    theme_bw() +
    theme(legend.position = "bottom") 
```

## `data` in geoms
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point() 


central_park = 
  weather_df %>% 
  filter(name == "CentralPark_NY")

waikiki = 
  weather_df %>% 
  filter(name == "Waikiki_HA")

ggplot(data = waikiki, aes(x = date, y = tmax, color = name)) + 
  geom_point() + 
  geom_line(data = central_park)

```

## Patchwork

```{r}
tmax_tmin_p = 
  weather_df %>% 
  ggplot(aes(x = tmax, y = tmin, color = name)) + 
  geom_point(alpha = .5) +
  theme(legend.position = "none")

prcp_dens_p = 
  weather_df %>% 
  filter(prcp > 0) %>% 
  ggplot(aes(x = prcp, fill = name)) + 
  geom_density(alpha = .5) + 
  theme(legend.position = "none")

tmax_date_p = 
  weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  theme(legend.position = "bottom")

(tmax_tmin_p + prcp_dens_p) / tmax_date_p
```

## Data manipulation
```{r}
weather_df %>% 
  mutate (
    name = fct_reorder (name, tmax)
  ) %>% 
  ggplot(aes (x=name , y =tmax)) + geom_boxplot()
```


What about tmax and tmin...
```{r}
weather_df %>% 
  pivot_longer (
    tmax:tmin,
    names_to = "obs",
    values_to = "temperature"
  ) %>% 
  ggplot(aes(x=temperature, fill = obs)) +
  geom_density (alpha =0.3) +
  facet_grid(.~ name)
```


```{r}
pulse_df =
  haven :: read_sas("/Users/gaoyang/P8105/data_wrangling_1/datasets/public_pulse_data.sas7bdat") %>% 
  janitor :: clean_names() %>% 
  pivot_longer(
    bdi_score_bl :bdi_score_12m,
    names_to = "visit",
    names_prefix ="bdi_score_",
    values_to = "bdi"
  ) %>% 
  mutate (visit= recode(visit, "bl" = "00m"),
          visit = factor(visit, levels = str_c(c("00", "01", "06", "12"), "m"))) %>% 
   arrange(id, visit)
 
ggplot(pulse_df, aes(x = visit, y = bdi)) + 
  geom_boxplot()

pulse_df 
```






