---
title: "ggplot2_part1"
author: "Yang Gao"
date: "10/5/2021"
output: github_document
---



```{r}
library(tidyverse)
library(ggridges)

knitr :: opts_chunk$set(
  fig.width =6, fig.asp = 0.6, out.width = "90%"
)
```

load in a dataset that we often use.
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Scatterplot
tmax vs tmin
```{r}
weather_df %>% 
  ggplot (aes (x= tmin, y= tmax)) + geom_point()

```


you can save ggplots
```{r}
ggp_tmax_tmin = 
  weather_df %>% 
  ggplot (aes (x= tmin, y= tmax)) + geom_point()

ggp_tmax_tmin


```
ggsave()

## fancy it up

color, ... other stuff

```{r}
weather_df %>% 
  ggplot (aes (x= tmin, y= tmax, color = name )) + geom_point(alpha=0.3) + geom_smooth( se=FALSE)

```

```{r}
weather_df %>% 
  ggplot (aes (x= tmin, y= tmax )) + geom_point(aes(color = name),alpha=0.3) + geom_smooth( se=FALSE)

```

```{r}
weather_df %>% 
  ggplot (aes (x= tmin, y= tmax, color = name )) + geom_point(alpha=0.3) + geom_smooth( se=FALSE)+
  facet_grid(.~ name)

```

more plots

```{r}
weather_df %>% 
  ggplot (aes(x= date, y= tmax, size = prcp)) + 
  geom_point(alpha =.3)+
  facet_grid(.~ name)+
  geom_smooth(se= FALSE) #se:standard error
```


## Use data manipulation as part of this

```{r}
weather_df %>% 
  filter (name =="CentralPark_NY") %>% 
  mutate(
    tmax = tmax * (9/5) + 32,
    tmin = tmin *(9/5) + 32
  ) %>% 
  ggplot(aes (x= tmin, y= tmax)) + geom_point()

```


## Stacking geoms
Which geoms do you want?

```{r}
weather_df %>% 
  ggplot(aes( x= date, y= tmax, color=name)) +
  geom_smooth() #only showing the smooth curve
```


```{r}
weather_df %>% 
  ggplot( aes(x= date, y= tmax)) +geom_hex()
```

```{r}
weather_df %>% 
  ggplot( aes(x= date, y= tmax)) +geom_bin_2d()
```



## Univariate plots
```{r}
weather_df %>% 
  ggplot (aes(x= tmax, fill = name)) +
  geom_histogram() +
  facet_grid((.~ name))
```

lets try other plots
```{r}
weather_df %>% 
  ggplot( aes(x= tmax, fill = name)) +
  geom_density(alpha = .3) #density plots
```


still with `tmax` and ``name`

```{r}
weather_df %>% 
  ggplot( aes( x = name, y = tmax))+geom_boxplot()
```

Some people like violin plots
```{r}
weather_df %>% 
  ggplot( aes( x = name, y = tmax))+geom_violin()
```


What about ridges...

```{r}
weather_df %>% 
  ggplot (aes( x= tmax, y = name)) +
  geom_density_ridges(scale=0.8)
```

## Embedding plots

```{r, fig.width = 7, fig.height = 5}
weather_df %>% 
  ggplot( aes(x=tmin, y =tmax, color = name)) +
  geom_point (alpha =.3)
```




